
# This test suite was initially generated by ChatGPT (GPT-5) and then edited by Brendan Wells.

import os
import sys
import math
from pathlib import Path
from datetime import datetime, timedelta, date

import numpy as np
import pandas as pd
import pytest

import holidays as ext_holidays  # external library
import holiday_smart

import importlib.util as _ilu

# Short aliases for things from the module under test
get_calendar = holiday_smart.get_calendar
detrend = holiday_smart.detrend
PaschalCycleHolidays = holiday_smart.PaschalCycleHolidays
IranInternetBlackout = holiday_smart.IranInternetBlackout
NO_PASCHAL_CYCLE = holiday_smart.NO_PASCHAL_CYCLE

# ----------
# Helpers
# ----------

def _transform_baseline_to_match_impl(country: str, years):
    """
    Build a baseline dict[date -> name] using ext_holidays but *apply the same text
    transformations* that get_calendar applies, so we can compare apples to apples.

    Mirrors the implementation:
      - Use getattr(ext_holidays, country)(years=years) except country=='ROW' which maps to US
      - Optionally append other calendars (we do not here)
      - Replace: r"Day off \\(substituted.*" -> "day off (substituted)"
      - Replace: " (observed)" -> ""  (case-sensitive in impl)
      - If not split: replace ';' with f"; {country}" (then prefix country + " ")
    """
    if country == "ROW":
        ch = ext_holidays.US(years=years)
    else:
        ch = getattr(ext_holidays, country)(years=years)

    # Convert to dict[date -> holiday string]; ext_holidays can have multiple per date
    # so we join duplicates with '; ' to mimic the impl's pre-split state.
    # Note: ext_holidays returns a HolidayBase which behaves like dict but supports multiple names.
    from collections import defaultdict
    names_by_date = defaultdict(list)
    for d, name in ch.items():
        names_by_date[d].append(str(name))

    out = {}
    for d, names in names_by_date.items():
        joined = "; ".join(names)
        # Apply the same string cleanup rules
        joined = pd.Series([joined]).str.replace(
            r"Day off \(substituted.*", "day off (substituted)", regex=True
        ).str.replace(" (observed)", "", regex=False).iloc[0]
        # Append country to each semicolon-separated segment (since split_concurrent_holidays=False in A1)
        joined = joined.replace(";", f"; {country}")
        # Prefix with country
        joined = f"{country} {joined}"
        out[d] = joined
    return out


# =========================
# A) get_calendar tests
# =========================

def test_A0_holidays_library_sanity():
    # Pragmatic guard; not a strict pin, but ensures the expected API exists.
    # This is a "not-super-kosher" check by design (documented with intent).
    assert hasattr(ext_holidays, "country_holidays") or hasattr(ext_holidays, "US")
    # Check a simple known date to catch major upstream changes quickly.
    us_2024 = ext_holidays.US(years=[2024])
    assert date(2024, 7, 4) in us_2024  # Independence Day presence


@pytest.mark.parametrize("country,years", [("US", [2024]), ("FR", [2024])])
def test_A1_full_parity_with_holidays(country, years):
    # Build expected baseline from external lib with the same text transforms.
    baseline = _transform_baseline_to_match_impl(country, years)
    # Call our function
    df = get_calendar(country=country, holiday_years=years, exclude_paschal_cycle=['US', 'FR'], split_concurrent_holidays=False)
    # Basic schema checks
    assert list(df.columns) == ["submission_date", "holiday", "country"]
    assert (df["country"] == country).all()
    assert np.issubdtype(df["submission_date"].dtype, np.datetime64)
    # Convert df to dict for comparison
    got = {pd.Timestamp(d).date(): h for d, h in zip(df["submission_date"], df["holiday"])}
    # Parity on the set of (date -> name). Upstream libraries occasionally add/correct holidays;
    # this test intentionally enforces exact parity to detect those changes.
    assert got == baseline


def test_A2_observed_cleanup_and_prefixing():
    # 2017 had New Year's Day observed in the US
    df = get_calendar(country="US", holiday_years=[2017])
    # No "(observed)" substrings should remain with this exact lowercase casing
    assert not df["holiday"].str.contains("(observed)", regex=False).any()
    # All names are prefixed with "US "
    assert df["holiday"].str.startswith("US ").all()


class SyntheticSubCalendar(ext_holidays.HolidayBase):
    def _populate(self, year):
        if year == 2024:
            # The implementation strips everything after "(substituted" and normalizes the phrase.
            self[date(2024, 5, 2)] = "Foo Day off (substituted from 2024-05-01)"


def test_A3_synthetic_substitution_normalization():
    df = get_calendar(
        country="US",
        holiday_years=[2024],
        split_concurrent_holidays=False,
        additional_holidays=[SyntheticSubCalendar],
    )
    # Find our synthetic entry
    row = df[df["submission_date"] == pd.Timestamp("2024-05-02")]
    assert not row.empty, "Synthetic substituted holiday not found"
    # Expect: country prefix and exact normalized phrase per implementation
    assert row.iloc[0]["holiday"] == "US Foo day off (substituted)"


def test_A4_split_concurrent_holidays_false():
    df = get_calendar(
        country="IR",
        holiday_years=[2025],
        split_concurrent_holidays=False,
        additional_holidays=[IranInternetBlackout],  # although module already adds for IR, keep explicit to test merge idempotence
    )
    blackout_dates = pd.date_range("2025-06-18", "2025-06-27", freq="D").date
    got_dates = set(pd.to_datetime(df["submission_date"]).dt.date)
    for d in blackout_dates:
        assert d in got_dates, f"Missing blackout date {d}"


def test_A5_split_concurrent_holidays_true():
    df = get_calendar(
        country="IR",
        holiday_years=[2025],
        split_concurrent_holidays=True,
        additional_holidays=[IranInternetBlackout],
    )
    # With no expected collisions, each blackout date should appear exactly once
    blackout_dates = pd.date_range("2025-06-18", "2025-06-27", freq="D")
    for d in blackout_dates:
        cnt = (df["submission_date"] == d).sum()
        assert cnt == 1, f"Expected exactly 1 row for {d.date()}, got {cnt}"
    # No semicolons in holiday names when split=True
    assert not df["holiday"].str.contains(";").any()


def test_A6_paschal_cycle():
    # Include for FR 2024
    df_fr = get_calendar(country="FR", holiday_years=[2024])
    easter_2024 = pd.Timestamp(holiday_smart.easter(2024))
    assert (df_fr["submission_date"] == easter_2024).any(), "Expected Easter Sunday in FR 2024 with paschal cycle"
    assert df_fr["holiday"].str.contains("FR Easter", regex=False).any()

    # Exclude for JP 2024 (JP is in NO_PASCHAL_CYCLE)
    assert "JP" in NO_PASCHAL_CYCLE
    df_jp = get_calendar(country="JP", holiday_years=[2024])
    assert not df_jp["holiday"].str.contains("Easter", case=False, regex=True).any()


def test_A7_sorting_and_uniqueness():
    df = get_calendar(country="US", holiday_years=[2023, 2024, 2025], split_concurrent_holidays=True)
    # Non-decreasing dates
    assert (df["submission_date"].sort_values().reset_index(drop=True) == df["submission_date"].reset_index(drop=True)).all()
    # Uniqueness of (date, holiday) when split=True
    assert not df.duplicated(subset=["submission_date", "holiday"]).any()


# =========================
# B) detrend tests
# =========================

def _simple_holiday_df(dates):
    return pd.DataFrame({"submission_date": pd.to_datetime(dates), "holiday": ["X"]*len(dates)})[["submission_date","holiday"]]

def test_B0_shape_and_finiteness():
    dates = pd.date_range("2025-05-15", periods=60, freq="D")
    y = pd.Series(np.full(len(dates), 100.0))
    h = _simple_holiday_df([dates[30]])  # one holiday near middle
    out = detrend(dates=dates, y=y, holiday_df=h, threshold=-0.05, min_radius=3, max_radius=7, spike_correction=1.0)
    assert isinstance(out, pd.Series)
    assert len(out) == len(y)
    assert np.isfinite(out.to_numpy()).all()
    # For a flat baseline, expect values to stay near baseline
    assert np.all((out.values >= 80) & (out.values <= 120))

@pytest.mark.parametrize("min_r,max_r", [(3,7), (1,3)])
@pytest.mark.parametrize("thr", [-0.10, 0.0])
@pytest.mark.parametrize("sc", [None, 1.0])
def test_B1_parameterization_smoke(min_r, max_r, thr, sc):
    dates = pd.date_range("2025-05-15", periods=60, freq="D")
    y = pd.Series(np.full(len(dates), 100.0))
    h = _simple_holiday_df([dates[10], dates[30], dates[50]])
    out = detrend(dates=dates, y=y, holiday_df=h, threshold=thr, min_radius=min_r, max_radius=max_r, spike_correction=sc)
    assert isinstance(out, pd.Series) and len(out) == len(y) and np.isfinite(out.to_numpy()).all()


def test_B2_empty_holiday_df_behavior():
    dates = pd.date_range("2025-05-15", periods=10, freq="D")
    y = pd.Series(np.full(len(dates), 100.0))
    h = _simple_holiday_df([]).iloc[:0]
    # Either raise or return a finite series; encode observed behavior.
    try:
        out = detrend(dates=dates, y=y, holiday_df=h)
        assert isinstance(out, pd.Series) and len(out) == len(y) and np.isfinite(out.to_numpy()).all()
    except Exception:
        # Accept raising behavior as a valid contract; the main point is that empty holiday_df is not allowed.
        pass


def test_B3_non_aligned_holidays():
    dates = pd.date_range("2025-05-15", periods=10, freq="D")
    y = pd.Series(np.full(len(dates), 100.0))
    outside = pd.Timestamp("2020-01-01")
    inside = dates[5]
    h = _simple_holiday_df([outside, inside])
    out = detrend(dates=dates, y=y, holiday_df=h)
    assert isinstance(out, pd.Series) and len(out) == len(y)
    assert np.isfinite(out.to_numpy()).all()


def test_B4_recorded_expected_output_with_slope():
    """
    Synthetic "actual behavior" regression test with a decreasing baseline.

    Baseline: linear from 100.0 (start) to 90.0 (end). On the middle day (index 29),
    we inject a drop to 80.0; holidays_df contains that middle day as a holiday.
    We record a "sensible" expected shape: a local triangular dip around the holiday,
    on top of the decreasing trend. If the implementation changes, update this golden.
    """
    dates = pd.date_range("2025-05-15", periods=60, freq="D")
    n = len(dates)
    baseline = pd.Series(np.linspace(100.0, 90.0, n))
    mid = 29
    y = baseline.copy()
    y.iloc[mid] = 80.0  # inject a deeper drop at the holiday

    h = _simple_holiday_df([dates[mid]])

    out = detrend(
        dates=dates,
        y=y,
        holiday_df=h,
        threshold=-0.05,
        min_radius=3,
        max_radius=7,
        spike_correction=1.0,
    )

    # "Recorded" expected: baseline with a symmetric triangular local dip of depth 10 centered at mid.
    # expected = baseline.copy()
    # for k, delta in [(-1, -5.0), (0, -10.0), (1, -5.0)]:
    #     if 0 <= mid + k < n:
    #         expected.iloc[mid + k] = baseline.iloc[mid + k] + delta
    expected = pd.Series([100.0, 99.83050847457628, 99.66101694915254, 99.49152542372882, 
    99.32203389830508, 99.15254237288136, 98.98305084745763, 98.8135593220339, 
    98.64406779661017, 98.47457627118644, 98.30508474576271, 98.13559322033899, 
    97.96610169491525, 97.79661016949153, 97.62711864406779, 97.45762711864407, 
    97.28813559322035, 97.11864406779661, 96.94915254237289, 96.77966101694915, 
    96.61016949152543, 96.44067796610169, 96.27118644067797, 96.10169491525424, 
    95.9322033898305, 95.76271186440678, 95.59322033898304, 95.42372881355932, 
    95.2542372881356, 95.08474576271186, 94.91525423728814, 94.7457627118644, 
    94.57627118644068, 94.40677966101696, 94.23728813559322, 94.0677966101695, 
    93.89830508474576, 93.72881355932203, 93.55932203389831, 93.38983050847457, 
    93.22033898305085, 93.05084745762711, 92.88135593220339, 92.71186440677965, 
    92.54237288135593, 92.37288135593221, 92.20338983050847, 92.03389830508475, 
    91.86440677966101, 91.69491525423729, 91.52542372881356, 91.35593220338983, 
    91.1864406779661, 91.01694915254237, 90.84745762711864, 90.67796610169492, 
    90.50847457627118, 90.33898305084746, 90.16949152542372, 90.0])

    # If you need to (re)generate the golden values from current algorithm, set UPDATE_B4_GOLDEN=1
    # and compare/print out.to_list(); then paste here.
    if os.getenv("UPDATE_B4_GOLDEN") == "1":
        print("CURRENT OUTPUT:", out.tolist())

    # Assert exact equality (float-safe via numpy allclose with tight tolerance)
    assert np.allclose(out.to_numpy(), expected.to_numpy(), rtol=0, atol=1e-9)


# =========================
# C) Edge/Regression tests
# =========================

def test_C1_large_input_performance_sanity():
    # 5 years of daily data
    dates = pd.date_range("2020-01-01", periods=365*5, freq="D")
    y = pd.Series(np.linspace(100.0, 120.0, len(dates)))
    # Holidays: monthly on the 15th
    hdates = pd.date_range(dates.min(), dates.max(), freq="MS") + pd.Timedelta(days=14)
    h = _simple_holiday_df(hdates)
    out = detrend(dates=dates, y=y, holiday_df=h, min_radius=3, max_radius=7)
    assert len(out) == len(y)
    assert np.isfinite(out.to_numpy()).all()

def test_C2_idempotence_wrt_extra_columns_and_order():
    dates = pd.date_range("2025-05-15", periods=60, freq="D")
    y = pd.Series(np.full(len(dates), 100.0))
    h = _simple_holiday_df([dates[10], dates[30]])
    h_extra = h.assign(dummy=1)[["holiday", "submission_date", "dummy"]]  # shuffled columns + extra
    out1 = detrend(dates=dates, y=y, holiday_df=h)
    out2 = detrend(dates=dates, y=y, holiday_df=h_extra)
    assert np.allclose(out1.to_numpy(), out2.to_numpy(), rtol=0, atol=1e-12)
